### ISSUE TITLE
Bro

### ISSUE THREAD

**Issue by kingsalman99** [SpookyTiang/OutlookEmailAccountCreator#1]
How to use that tools??

**Comment by SpookyTiang** [comment]
Hey Salman. I'm currently working on it and will post more updates alongside detailed instructions soon. Thanks for showing interest!

**Comment by kingsalman99** [comment]
Succes bro ,thax

Pada tanggal Min, 19 Jul 2020 08.59, Strange Quark <notifications@github.com>
menulis:
